services:
  componentsmanager:
    image: componentsmanager
    build:
      context: .
      dockerfile: ComponentsManager/Dockerfile

  console:
    image: console
    build:
      context: .
      dockerfile: Console/Dockerfile
