namespace DBManager.Const;

public enum BottomLevelCategory
{
    None,
    //resistor
    ResistorSMD,
    Shunt,
    ThroughHole,
    AluminiumCase,
    Array,
    Potentiometer,
    //Capacitor
    CapacitorCeramicSMD,
    CapacitorAluminiumSMD,
    CapacitorAluminiumLeaded,
    //Connectors
    TerminalBlock,
    USB,
    //Diodes
    Schottky,
    Switching,
    //CircuitProtection
    ESD,
    ResettableFuse,
    //Relay
    PowerRelay,
    //Coils
    InductorSMD,
    //Opto
    LedIndication,
    //Switches
    Tactile,
    //PowerManagement
    LDO,
    DCDC,
    //Transistor
    Mosfet,
    //ComunicationModule
    WiFi,
}